spring:
  # DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/market?serverTimezone=Asia/Seoul
    username: solution
    password: 1234

# 마이바티스 설정
mybatis:
  mapper-locations: classpath:static/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


